import mongoose from "mongoose";

const userSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    isAdmin: { type: Boolean, default: false },
    isSeller: { type: Boolean, default: false },
    seller: {
      name: { type: String, default: "Nameless Seller" },
      logo: String,
      description: String,
      rating: { type: Number, default: 0 },
      numReviews: { type: Number, default: 0 },
      shipping: {
        Adrar: { type: String, default: 400 },
        Chlef: { type: String, default: 400 },
        Laghouat: { type: String, default: 400 },
        OumElBouaghi: { type: String, default: 400 },
        Batna: { type: String, default: 400 },
        Béjaïa: { type: String, default: 400 },
        Biskra: { type: String, default: 400 },
        Béchar: { type: String, default: 400 },
        Blida: { type: String, default: 400 },
        Bouira: { type: String, default: 400 },
        Tamanrasset: { type: String, default: 400 },
        Tébessa: { type: String, default: 400 },
        Tlemcen: { type: String, default: 400 },
        Tiaret: { type: String, default: 400 },
        TiziOuzou: { type: String, default: 400 },
        Alger: { type: String, default: 400 },
        Djelfa: { type: String, default: 400 },
        Jijel: { type: String, default: 400 },
        Sétif: { type: String, default: 400 },
        Saïda: { type: String, default: 400 },
        Skikda: { type: String, default: 400 },
        SidiBelAbbès: { type: String, default: 400 },
        Annaba: { type: String, default: 400 },
        Guelma: { type: String, default: 400 },
        Constantine: { type: String, default: 400 },
        Médéa: { type: String, default: 400 },
        Mostaganem: { type: String, default: 400 },
        MSila: { type: String, default: 400 },
        Mascara: { type: String, default: 400 },
        Ouargla: { type: String, default: 400 },
        Oran: { type: String, default: 400 },
        ElBayadh: { type: String, default: 400 },
        Illizi: { type: String, default: 400 },
        BordjBouArreridj: { type: String, default: 400 },
        Boumerdès: { type: String, default: 400 },
        ElTarf: { type: String, default: 400 },
        Tindouf: { type: String, default: 400 },
        Tissemsilt: { type: String, default: 400 },
        ElOued: { type: String, default: 400 },
        Khenchela: { type: String, default: 400 },
        SoukAhras: { type: String, default: 400 },
        Tipaza: { type: String, default: 400 },
        Mila: { type: String, default: 400 },
        AïnDefla: { type: String, default: 400 },
        Naâma: { type: String, default: 400 },
        AïnTémouchent: { type: String, default: 400 },
        Ghardaïa: { type: String, default: 400 },
        Relizane: { type: String, default: 400 },
      },
    },
  },
  {
    timestamps: true,
  }
);
const User = mongoose.model("User", userSchema);
export default User;
